version: "3"
services:
  pi5-pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    volumes:
      - "./pihole:/etc/pihole"
      - "./dnsmasq.d:/etc/dnsmasq.d"
    environment:
      TZ: "Europe/Berline"
    restart: unless-stopped
